AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - "https://d3u8od6g4wwl6c.cloudfront.net" # Your callback URL on S3
      SupportedIdentityProviders:
        - COGNITO
  
  WordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WordsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: LanguageWord
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: LanguageWord
          KeyType: RANGE
        
  QueryCountersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QueryCountersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: Ttl
        Enabled: true
        
  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatHistoryTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: Ttl
        Enabled: true
      
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TalkToMe
      CodeUri: ./bin/Release/net8.0/publish
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - AWSLambda_FullAccess           # Full access to Lambda resources
        - AmazonS3FullAccess             # Full access to S3 resources
        - AmazonTranscribeFullAccess      # Full access to Amazon Transcribe
        - AmazonPollyFullAccess           # Full access to Amazon Polly
        - AmazonBedrockFullAccess         # Full access to Amazon Bedrock
        - AmazonDynamoDBFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "cognito:GetUser"     # Allow getting user details
                - "cognito:ListUsers"    # Optional: List users in the user pool
                - "cognito:AdminGetUser"
              Resource:
                - "arn:aws:cognito-idp:us-east-1:038462779690:userpool/us-east-1_walDCpNcK"
      Events:
        ProcessTextApi:
          Type: 'Api'
          Properties:
            Path: '/{proxy+}'
            Method: 'ANY'