name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write
  actions: write
  
jobs:
  dev-deployment:
    name: Deploy to Dev
    uses: ./.github/workflows/cicd.yml
    with:
      environment: 'dev'

  prod-deployment:
    name: Deploy to Prod
    needs: dev-deployment  # Run this only after dev-deployment succeeds
    uses: ./.github/workflows/cicd.yml
    with:
      environment: 'prod'