name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  dev-deployment:
    name: Deploy to Dev
    uses: ./.github/workflows/cicd.yml
    with:
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  prod-deployment:
    name: Deploy to Prod
    needs: dev-deployment  # Run this only after dev-deployment succeeds
    uses: ./.github/workflows/cicd.yml
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }} 